redirect_guide_2025:
  path: topic/creation-de-sites-internet-en-brabant-wallon-guide-2025
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_vitrine_cse:
  path: focus-sur/site-vitrine-court-saint-etienne
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /focus-sur/creation-site-vitrine-court-saint-etienne
    permanent: true

redirect_removed_to_guide_2025:
  path: focus-sur/pourquoi-investir-creation-site-internet-votre-entreprise
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_old_slug:
  path: /topic/developpeur-web-en-brabant-wallon-comment-choisir-le-bon-partenaire-pour-votre-projet
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_old_slug_liege:
  path: /topic/creation-de-sites-internet-a-liege-un-service-professionnel-et-local
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-web-liege
    permanent: true

redirect_old_carte_visite:
  path: /service/carte-de-visite-numerique
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: creation
    slug: creation-site-web-carte-de-visite

redirect_old_gcb:
  path: /realisation/site-web-les-gais-carabiniers-de-bernissart
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /realisation/digitalisation-et-Référencement-local-pour-les-gais-carabiniers
    permanent: true

redirect_old_gcb_2:
  path: /realisation/digitalisation-et-Référencement-local-pour-les-gais-carabiniers
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /realisation/digitalisation-et-referencement-local-pour-les-gais-carabiniers
    permanent: true

redirect_coming_soon:
  path: /focus-sur/page-coming-soon
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /focus-sur/creer-page-coming-soon
    permanent: true

redirect_coming_soon_service:
  path: /service/une-page-coming-soon
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /focus-sur/creer-page-coming-soon
    permanent: true

focus_index_redirect:
  path: /focus
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /
    permanent: true
    
redirect_service_creation_vitrine:
  path: /service/creation-de-site-vitrine
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: creation
    slug: creation-de-site-vitrine

redirect_service_carte_visite:
  path: /service/creation-site-web-carte-de-visite
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: creation
    slug: creation-site-web-carte-de-visite

redirect_service_horeca:
  path: /service/site-vitrine-horeca-cle-en-main
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: creation
    slug: site-vitrine-horeca-cle-en-main

redirect_service_landing_page:
  path: /service/landing-page-soyez-visible-avec-page-accueil-professionnelle
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: creation
    slug: landing-page-soyez-visible-avec-page-accueil-professionnelle

redirect_service_refonte:
  path: /service/refonte-et-amelioration-de-site-web
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: evolution
    slug: refonte-et-amelioration-de-site-web

redirect_service_referencement:
  path: /service/referencement-local-court-saint-etienne
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_work_show
    permanent: true
    type: evolution
    slug: referencement-local-court-saint-etienne

controllers:
  resource: ../src/Controller/
  type: attribute
