redirect_guide_2025:
  path: topic/creation-de-sites-internet-en-brabant-wallon-guide-2025
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_vitrine_cse:
  path: focus-sur/site-vitrine-court-saint-etienne
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /focus-sur/creation-site-vitrine-court-saint-etienne
    permanent: true

redirect_removed_to_guide_2025:
  path: focus-sur/pourquoi-investir-creation-site-internet-votre-entreprise
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_old_slug:
  path: /topic/developpeur-web-en-brabant-wallon-comment-choisir-le-bon-partenaire-pour-votre-projet
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-internet-brabant-wallon
    permanent: true

redirect_old_slug_liege:
  path: /topic/creation-de-sites-internet-a-liege-un-service-professionnel-et-local
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /creation-site-web-liege
    permanent: true

redirect_old_carte_visite:
  path: /service/carte-de-visite-numerique
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /service/creation-site-web-carte-de-visite
    permanent: true

redirect_old_gcb:
  path: /realisation/site-web-les-gais-carabiniers-de-bernissart
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /realisation/digitalisation-et-Référencement-local-pour-les-gais-carabiniers
    permanent: true

redirect_old_gcb_2:
  path: /realisation/digitalisation-et-Référencement-local-pour-les-gais-carabiniers
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /realisation/digitalisation-et-referencement-local-pour-les-gais-carabiniers
    permanent: true

redirect_coming_soon:
  path: /focus-sur/page-coming-soon
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /focus-sur/creer-page-coming-soon
    permanent: true

focus_index_redirect:
  path: /focus
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    url: /
    permanent: true

controllers:
  resource: ../src/Controller/
  type: attribute
